# Generated by Django 5.1.5 on 2025-01-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос - ответ', 'verbose_name_plural': 'Вопрос - ответ'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='subcategorycategory',
            options={'verbose_name': 'Подкатегория-категория', 'verbose_name_plural': 'Подкатегории-категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategorygoods',
            options={'verbose_name': 'Подкатегория-товар', 'verbose_name_plural': 'Подкатегории-товары'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userbucket',
            options={'verbose_name': 'Пользователь - предмет - количество', 'verbose_name_plural': 'Пользователь - предмет - количество'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='goods',
            name='caption',
            field=models.CharField(blank=True, max_length=950),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(),
        ),
    ]
